FROM phpswoole/swoole:php7.4-alpine

COPY . /FlashDetector/
WORKDIR /FlashDetector/FlashDetector/
RUN apk add --no-cache git; \
    composer install

FROM phpswoole/swoole:php7.4-alpine

COPY --from=0 /FlashDetector /FlashDetector
WORKDIR /FlashDetector/Scripts/

EXPOSE 8080

CMD ["php", "ws.php", "-a", "0.0.0.0", "-p", "8080", "-s"]
